/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sitema_bancario;

import Conexao.HibernateUtil;
import classes.Cliente;
import classes.Conta;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author carlo
 */
public class AConta extends javax.swing.JInternalFrame {

    /**
     * Creates new form NCConta
     */
    public AConta() {
        initComponents();
    }
 
    private void AtualizarCliente(){
        Cliente cliente = PesquisarCliente();
        cliente.setNome(TNome.getText());
        cliente.setProfissao(TProfissao.getText());
        cliente.setRua(TRua.getText());
        cliente.setComplemento(TComplemento.getText());
        cliente.setBairro(TBairro.getText());
        cliente.setCidade(TCidade.getText());
        cliente.setEstado(TEstado.getText());
        cliente.setCep(TCidade.getText());
        cliente.setTelefone(TTelefone.getText());
        Session s = HibernateUtil.getSessionFactory().getCurrentSession();
        s.beginTransaction();
        s.merge(cliente);
        s.getTransaction().commit();
        JOptionPane.showMessageDialog(null, "Dados do cliente atualizado com sucesso!");
        this.dispose();
    }
    
    private Cliente PesquisarCliente(){
        Session s = HibernateUtil.getSessionFactory().getCurrentSession();
        s.beginTransaction();
        Cliente i=null;
        List<Cliente> lista = (List<Cliente>)s.createQuery("From Cliente").list();
        for(Cliente c : lista){
            if(c.getCpf().equals(TCPFOURG.getText()) || c.getRg().equals(TCPFOURG.getText())){
                i = c;
                //s.getTransaction().commit();
                break;
            }
        }
        if(i == null){
            JOptionPane.showMessageDialog(null, "Cliente nao cadastrado!");
        }
        s.getTransaction().commit();
        return i;
    }
    
    private void SetDados(){
        Cliente cliente = PesquisarCliente();
        TNome.setText(cliente.getNome());
        TProfissao.setText(cliente.getProfissao());
        TTelefone.setText(cliente.getTelefone());
        TRua.setText(cliente.getRua());
        TComplemento.setText(cliente.getComplemento());
        TBairro.setText(cliente.getBairro());
        TCidade.setText(cliente.getCidade());
        TEstado.setText(cliente.getEstado());
        TCep.setText(cliente.getCep());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TCPFOURG = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TProfissao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TRua = new javax.swing.JTextField();
        TComplemento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TBairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TCidade = new javax.swing.JTextField();
        TEstado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TCep = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TTelefone = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BConfirmar = new javax.swing.JButton();
        BPesquisar = new javax.swing.JButton();
        TNome = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("CPF OU RG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 93, -1));

        TCPFOURG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCPFOURGActionPerformed(evt);
            }
        });
        TCPFOURG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCPFOURGKeyPressed(evt);
            }
        });
        jPanel1.add(TCPFOURG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 181, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 26));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("PROFISSAO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 107, -1));
        jPanel1.add(TProfissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 162, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("RUA");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, -1));
        jPanel1.add(TRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 30));
        jPanel1.add(TComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("COMPLEMENTO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 120, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("BAIRRO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 20));
        jPanel1.add(TBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 228, 23));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("CIDADE");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 78, 23));
        jPanel1.add(TCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 228, 26));
        jPanel1.add(TEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 228, 26));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("ESTADO");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 82, 23));
        jPanel1.add(TCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 161, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("CEP");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 81, 19));
        jPanel1.add(TTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 161, 30));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("TELEFONE");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 126, 20));

        BConfirmar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BConfirmar.setText("ATUALIZAR");
        BConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(BConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 120, 40));

        BPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BPesquisar.setText("PESQUISAR");
        BPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPesquisarActionPerformed(evt);
            }
        });
        BPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BPesquisarKeyPressed(evt);
            }
        });
        jPanel1.add(BPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 30, -1, -1));
        jPanel1.add(TNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 390, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCPFOURGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCPFOURGKeyPressed
        // TODO add your handling code here:
                if(evt.getKeyCode()== KeyEvent.VK_ENTER){
                        SetDados();
                }
       
    }//GEN-LAST:event_TCPFOURGKeyPressed

    private void TCPFOURGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCPFOURGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCPFOURGActionPerformed

    private void BConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConfirmarActionPerformed
        // TODO add your handling code here:
        AtualizarCliente();
    }//GEN-LAST:event_BConfirmarActionPerformed

    private void BPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPesquisarActionPerformed
        // TODO add your handling code here:
        SetDados();
    }//GEN-LAST:event_BPesquisarActionPerformed

    private void BPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BPesquisarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            SetDados();
        }
    }//GEN-LAST:event_BPesquisarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConfirmar;
    private javax.swing.JButton BPesquisar;
    private javax.swing.JTextField TBairro;
    private javax.swing.JTextField TCPFOURG;
    private javax.swing.JTextField TCep;
    private javax.swing.JTextField TCidade;
    private javax.swing.JTextField TComplemento;
    private javax.swing.JTextField TEstado;
    private javax.swing.JTextField TNome;
    private javax.swing.JTextField TProfissao;
    private javax.swing.JTextField TRua;
    private javax.swing.JTextField TTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
