/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sitema_bancario;

/**
 *
 * @author carlo
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaInterna = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Banco = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        JC = new javax.swing.JMenuItem();
        MAtualizar = new javax.swing.JMenuItem();
        Novos = new javax.swing.JMenuItem();
        MExcluir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Gerar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaInterna.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout TelaInternaLayout = new javax.swing.GroupLayout(TelaInterna);
        TelaInterna.setLayout(TelaInternaLayout);
        TelaInternaLayout.setHorizontalGroup(
            TelaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        TelaInternaLayout.setVerticalGroup(
            TelaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastar");

        Banco.setText("Banco");
        Banco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BancoActionPerformed(evt);
            }
        });
        jMenu1.add(Banco);

        jMenu3.setText("Conta");

        jMenu4.setText("Cadastrar");

        JC.setText("Já cadastrado");
        JC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCActionPerformed(evt);
            }
        });
        jMenu4.add(JC);

        MAtualizar.setText("Atualizar");
        MAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAtualizarActionPerformed(evt);
            }
        });
        jMenu4.add(MAtualizar);

        Novos.setText("Novos");
        Novos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovosActionPerformed(evt);
            }
        });
        jMenu4.add(Novos);

        jMenu3.add(jMenu4);

        MExcluir.setText("Excluir");
        MExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MExcluirActionPerformed(evt);
            }
        });
        jMenu3.add(MExcluir);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatorios");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        Gerar.setText("Gerar");
        Gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarActionPerformed(evt);
            }
        });
        jMenu2.add(Gerar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaInterna)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaInterna)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BancoActionPerformed
        // TODO add your handling code here:
        Banco banco = new Banco();
        TelaInterna.add(banco);
        banco.setLocation(TelaInterna.getSize().width/2,TelaInterna.getSize().height/2);
        banco.setVisible(true);
//        try {   
//            banco.setSelected(true);         
//            banco.setMaximum(true);   
//        } catch (java.beans.PropertyVetoException e) {}
    }//GEN-LAST:event_BancoActionPerformed

    private void JCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCActionPerformed
        // TODO add your handling code here:
        JCConta conta = new JCConta();
        TelaInterna.add(conta);
        conta.setVisible(true);
//        try {   
//            conta.setSelected(true);         
//            conta.setMaximum(true);   
//        } catch (java.beans.PropertyVetoException e) {}
    }//GEN-LAST:event_JCActionPerformed

    private void NovosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovosActionPerformed
        // TODO add your handling code here:
        NCConta conta = new NCConta();
        TelaInterna.add(conta);
        conta.setVisible(true);
    }//GEN-LAST:event_NovosActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void GerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarActionPerformed
        // TODO add your handling code here:
        RBanco banco = new RBanco();
        TelaInterna.add(banco);
        banco.setVisible(true);
    }//GEN-LAST:event_GerarActionPerformed

    private void MAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAtualizarActionPerformed
        // TODO add your handling code here:
        AConta aconta = new AConta();
        TelaInterna.add(aconta);
        aconta.setVisible(true);
    }//GEN-LAST:event_MAtualizarActionPerformed

    private void MExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MExcluirActionPerformed
        // TODO add your handling code here:
        ExcluirConta excluirconta = new ExcluirConta();
        TelaInterna.add(excluirconta);
        excluirconta.setVisible(true);
    }//GEN-LAST:event_MExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Admin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Banco;
    private javax.swing.JMenuItem Gerar;
    private javax.swing.JMenuItem JC;
    private javax.swing.JMenuItem MAtualizar;
    private javax.swing.JMenuItem MExcluir;
    private javax.swing.JMenuItem Novos;
    private javax.swing.JDesktopPane TelaInterna;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
