/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sitema_bancario;

import Conexao.HibernateUtil;
import classes.Conta;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author carlo
 */
public class ExcluirConta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Banco
     */
    public ExcluirConta() {
        initComponents();
    }
    private void excluir(Conta conta){
        Session s = HibernateUtil.getSessionFactory().getCurrentSession();
        s.beginTransaction();
        s.delete(conta);
        s.getTransaction().commit();
        JOptionPane.showMessageDialog(null, "Conta apagada com sucesso!");
        this.dispose();
    }
    private Conta PesquisarConta(){
        Session s = HibernateUtil.getSessionFactory().getCurrentSession();
        s.beginTransaction();
        Conta i = null;
        List<Conta> lista = (List<Conta>)s.createQuery("From Conta").list();
        for(Conta c : lista){
            if(c.getIdConta().equals(Integer.parseInt(TConta.getText())) || c.getAgencia().equals(Integer.parseInt(TAgencia.getText()))){
                i = c;
                //s.getTransaction().commit();
                break;
            }
        }
        if(i == null){
            JOptionPane.showMessageDialog(null, "Cliente nao cadastrado!");
        }else if(i.getValor() > 0){
            JOptionPane.showMessageDialog(null, "Conta nao pode ser apagada pois contem o valor de R$"+i.getValor());
            i = null;
        }
        s.getTransaction().commit();
        return i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l = new javax.swing.JLabel();
        TConta = new javax.swing.JTextField();
        Confirma = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        TAgencia = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        l.setText("CONTA");
        jPanel1.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        TConta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(TConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 86, -1));

        Confirma.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Confirma.setText("Confirma");
        Confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaActionPerformed(evt);
            }
        });
        jPanel1.add(Confirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        Cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        TAgencia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(TAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 86, -1));

        l1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        l1.setText("AGENCIA");
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaActionPerformed
        // TODO add your handling code here:
        Conta conta = PesquisarConta();
        if(conta == null){
            
        }else{
            excluir(conta);
        }
        
    }//GEN-LAST:event_ConfirmaActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Confirma;
    private javax.swing.JTextField TAgencia;
    private javax.swing.JTextField TConta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
