/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sitema_bancario;

import Conexao.HibernateUtil;
import classes.Agencia;
import classes.Cliente;
import classes.Conta;
import classes.Extrato;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.hibernate.Session;

/**
 *
 * @author carlo
 */
public class RBanco extends javax.swing.JInternalFrame {

    /**
     * Creates new form Extrato
     */
    public RBanco() {
        initComponents();
    }
    
    public void QCliente(){
        Session s = HibernateUtil.getSessionFactory().getCurrentSession();
        s.beginTransaction();
        List<Cliente> lista = (List<Cliente>)s.createQuery("From Cliente").list();
        s.getTransaction().commit();
        JOptionPane.showMessageDialog(null, "Existe "+lista.size()+" clientes cadastrados");
    }
    
    public void QBanco(){
        Session s = HibernateUtil.getSessionFactory().getCurrentSession();
        s.beginTransaction();
        List<Agencia> lista = (List<Agencia>)s.createQuery("From Agencia").list();
        JOptionPane.showMessageDialog(null, "Existe "+lista.size()+" bancos cadastrados");
        s.getTransaction().commit();
    }
    
    public void QContas(){
        Session s = HibernateUtil.getSessionFactory().getCurrentSession();
        s.beginTransaction();
        List<Conta> lista = (List<Conta>)s.createQuery("From Conta").list();
        JOptionPane.showMessageDialog(null, "Existe "+lista.size()+" Contas cadastradas");
        s.getTransaction().commit();
    }
    public void QDinheiro(){
        Session s = HibernateUtil.getSessionFactory().getCurrentSession();
        s.beginTransaction();
        List<Conta> lista = (List<Conta>)s.createQuery("From Conta").list();
        JOptionPane.showMessageDialog(null, "Existe "+lista.size()+" Contas cadastradas");
        s.getTransaction().commit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CBRelatorio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BPesquisar = new javax.swing.JButton();

        setClosable(true);

        CBRelatorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CBRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENTES", "BANCO", "CONTAS" }));
        CBRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBRelatorioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("SELECIONE A OPCÃO DE RELATORIO");

        BPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BPesquisar.setText("PESQUISAR");
        BPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(CBRelatorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(112, 112, 112)
                .addComponent(BPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CBRelatorio))
                    .addComponent(BPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBRelatorioActionPerformed

    private void BPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPesquisarActionPerformed
        // TODO add your handling code here:
        if(CBRelatorio.getSelectedItem().toString().equals("CLIENTES")) QCliente();
        if(CBRelatorio.getSelectedItem().toString().equals("BANCO")) QBanco();
        if(CBRelatorio.getSelectedItem().toString().equals("CONTAS")) QContas();
    }//GEN-LAST:event_BPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPesquisar;
    private javax.swing.JComboBox<String> CBRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
