package classes;
// Generated 07/05/2018 22:38:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Agencia generated by hbm2java
 */
public class Agencia  implements java.io.Serializable {


     private Integer idAgencia;
     private String nome;
     private Set contas = new HashSet(0);

    public Agencia() {
    }

	
    public Agencia(String nome) {
        this.nome = nome;
    }
    public Agencia(String nome, Set contas) {
       this.nome = nome;
       this.contas = contas;
    }
   
    public Integer getIdAgencia() {
        return this.idAgencia;
    }
    
    public void setIdAgencia(Integer idAgencia) {
        this.idAgencia = idAgencia;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getContas() {
        return this.contas;
    }
    
    public void setContas(Set contas) {
        this.contas = contas;
    }




}


