package classes;
// Generated 07/05/2018 22:38:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Conta generated by hbm2java
 */
public class Conta  implements java.io.Serializable {


     private Integer idConta;
     private Agencia agencia;
     private Cliente cliente;
     private float valor;
     private String senha;
     private Set transferenciasForContaDestino = new HashSet(0);
     private Set transferenciasForAgenciaDestino = new HashSet(0);

    public Conta() {
    }

	
    public Conta(Agencia agencia, Cliente cliente, float valor, String senha) {
        this.agencia = agencia;
        this.cliente = cliente;
        this.valor = valor;
        this.senha = senha;
    }
    public Conta(Agencia agencia, Cliente cliente, float valor, String senha, Set transferenciasForContaDestino, Set transferenciasForAgenciaDestino) {
       this.agencia = agencia;
       this.cliente = cliente;
       this.valor = valor;
       this.senha = senha;
       this.transferenciasForContaDestino = transferenciasForContaDestino;
       this.transferenciasForAgenciaDestino = transferenciasForAgenciaDestino;
    }
   
    public Integer getIdConta() {
        return this.idConta;
    }
    
    public void setIdConta(Integer idConta) {
        this.idConta = idConta;
    }
    public Agencia getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getTransferenciasForContaDestino() {
        return this.transferenciasForContaDestino;
    }
    
    public void setTransferenciasForContaDestino(Set transferenciasForContaDestino) {
        this.transferenciasForContaDestino = transferenciasForContaDestino;
    }
    public Set getTransferenciasForAgenciaDestino() {
        return this.transferenciasForAgenciaDestino;
    }
    
    public void setTransferenciasForAgenciaDestino(Set transferenciasForAgenciaDestino) {
        this.transferenciasForAgenciaDestino = transferenciasForAgenciaDestino;
    }




}


