package classes;
// Generated 07/05/2018 22:38:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Extrato generated by hbm2java
 */
public class Extrato  implements java.io.Serializable {


     private Integer idExtrato;
     private String descricao;
     private float valor;
     private String servico;
     private Date data;
     private int conta;

    public Extrato() {
    }

	
    public Extrato(float valor, String servico, Date data, int conta) {
        this.valor = valor;
        this.servico = servico;
        this.data = data;
        this.conta = conta;
    }
    public Extrato(String descricao, float valor, String servico, Date data, int conta) {
       this.descricao = descricao;
       this.valor = valor;
       this.servico = servico;
       this.data = data;
       this.conta = conta;
    }
   
    public Integer getIdExtrato() {
        return this.idExtrato;
    }
    
    public void setIdExtrato(Integer idExtrato) {
        this.idExtrato = idExtrato;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }
    public String getServico() {
        return this.servico;
    }
    
    public void setServico(String servico) {
        this.servico = servico;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getConta() {
        return this.conta;
    }
    
    public void setConta(int conta) {
        this.conta = conta;
    }




}


